export const actions = {
	SEND_MESSAGE: 'SEND_MESSAGE',
	SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
	SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',

	FETCH_USER: 'FETCH_USER',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILED: 'FETCH_USER_FAILED',
};
